module.exports = {
  DELETE_POST: 'DELETE_POST',
  EDIT_POST: 'EDIT_POST',
  ADD_POST: 'ADD_POST',
  GET_POSTS_LIST: 'GET_POSTS_LIST',
  POST_PROP_CHANGED: 'POST_PROP_CHANGED',
  GET_COMMENTS_LIST: 'GET_COMMENTS_LIST',
};
